import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // Main docs
    'intro',
    'dsl-overview',
    {
      type: 'category',
      label: 'Map Elements',
      link: { type: 'generated-index' },
      items: [
        'map-elements/anchor',
        'map-elements/component',
        'map-elements/link',
        'map-elements/evolution',
        'map-elements/inertia',
        'map-elements/pipeline',
        'map-elements/build-buy-outsource',
        'map-elements/market',
        'map-elements/accelerator',
        'map-elements/pst',
        'map-elements/note',
        'map-elements/annotations',
        'map-elements/submap',
      ]
    },
    {
      type: 'category',
      label: 'Map Features',
      link: { type: 'generated-index' },
      items: [
        { type: 'autogenerated', dirName: 'map-features' }
      ]
    },
    'examples',
    // Visual separation for integrations
    { type: 'html', value: '<hr style="margin: 1em 0;">' },
    'vscode-extension',
    'obsidian-plugin'
  ],
};

export default sidebars;
